# .github/workflows/ci.yml

name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check out code
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # Use the latest lts version of node
          node-version: 'lts/*'
          # Cache npm dependencies so they don't have to be downloaded next time - https://github.com/actions/setup-node#caching-packages-dependencies
          cache: 'npm'

      - name: Install node dependencies
        # Use `ci` vs. `install`, see https://docs.npmjs.com/cli/v8/commands/npm-ci
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  # Uncomment the following to run unit tests once you have them
  # unit-tests:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4

  #     - name: Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 'lts/*'
  #         cache: 'npm'
  #     - name: Install node dependencies and run tests
  #       # Runs `npm ci` and `npm test` in one step. See: https://docs.npmjs.com/cli/v8/commands/npm-install-ci-test
  #       run: npm install-ci-test
